linters:
  enable:
    - copyloopvar 
    - gofmt
    - goimports
    - gosec
    - ineffassign
    - misspell
    - nolintlint
    - revive
    - staticcheck
    - tenv 
    - unconvert
    - unused
    - govet
    - dupword 